//Music types
export const GET_MUSIC_ALL = 'GET_MUSIC_ALL';
export const GET_MUSIC_FAIL = 'GET_MUSIC_FAIL';

export const ADD_ARTIST_SUCCESS = 'ADD_ARTIST_SUCCESS';
export const ADD_ARTIST_FAIL = 'ADD_ARTIST_FAIL';

export const ADD_MUSIC_SUCCESS = 'ADD_MUSIC_SUCCESS';
export const ADD_MUSIC_FAIL = 'ADD_MUSIC_FAIL';

export const GET_ARTIS_ALL = 'GET_ARTIS_ALL';
export const GET_ARTIS_FAIL = 'GET_ARTIS_FAIL';

export const ERROR = 'ERROR';

//Login & Auth types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';

export const FAKE_LOGIN = 'FAKE_LOGIN';

//Payment
export const PAYMENT_ERROR = 'PAYMENT_ERROR';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';

export const GET_TRANSACTION_SUCCESS = 'GET_TRANSACTION_SUCCESS';
export const GET_TRANSACTION_ERROR = 'GET_TRANSACTION_ERROR';

export const PAYMENT_UPDATE_SUCCES = 'PAYMENT_UPDATE_SUCCES';
export const PAYMENT_UPDATE_FAIL = 'PAYMENT_UPDATE_FAIL';
